module.exports = {
  data: [
  [
  { title: 'CannaCo',
    description: 'CannaCo is an International Architecture Competition entry held by the Bee Breeders Architecture Competition Organizers to design a theoretical Cannabis Bank. CannaCo placed in the Top 40, qualifying for the final round of the international competition. ',
    tools: 'Rhino, Sketchup, AutoCAD, V-Ray, Illustrator, and Photoshop',
    teamImage: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/SamZoll-Logo-2017.svg',
    team: 'Army of 1',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo-Logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo+-+1.jpg'},
  { title: 'CannaCo',
    topic: 'UX DESIGN',
    tools: 'Rhino, Sketchup, AutoCAD, V-Ray, Illustrator, and Photoshop',
    description: 'Slide 2.',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo-Logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo+-+2.jpg'},
  { title: 'CannaCo',
    topic: 'UX DESIGN',
    tools: 'Rhino, Sketchup, AutoCAD, V-Ray, Illustrator, and Photoshop',
    description: 'Slide 3.',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo-Logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo+-+3.jpg'
  },
  { title: 'CannaCo',
    topic: 'UX DESIGN',
    tools: 'Rhino, Sketchup, AutoCAD, V-Ray, Illustrator, and Photoshop',
    description: 'Slide 4.',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo-Logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo+-+4.jpg'
  }],
  [
  { title: 'Trivia Monster',
    description: 'Trivia Monster is the third generation of the trivios games. It is currently still in production but coming soon. Trivia Monster is a real-time trivia tournament game where players compete for real prizes. This view shows the game lobby and tournament navigation.',
    tools: 'Illustrator, Photoshop and Xcode',
    teamImage: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/400X-Baby-Gator.png',
    team: 'Purple Gator',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/triviaMonster/New-TM-Icon2-rounded.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/triviaMonster/Monster-Homepage.png'},
  { title: 'Trivia Monster',
    topic: 'UI DESIGN - HomeScreen',
    tools: 'Illustrator',
    description: 'This is a detailed mockup of the Trivia Monster HomeScreen',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/triviaMonster/New-TM-Icon2-rounded.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/triviaMonster/HomeScreen.png'},
  { title: 'Trivia Monster',
    topic: 'UI DESIGN - Gameplay',
    tools: 'Illustrator',
    description: 'This is a detailed mockup of the trivia gameplay.',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/triviaMonster/New-TM-Icon2-rounded.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/triviaMonster/Gameplay.png'
  }],
  [
  { title: 'Double Luck Nudge Slots',
    description: 'Double Luck Nudge is an Apple Watch slot machine on your wrist. Based off real Las Vegas Slot machines, Just tap the slot machine on your Watch and hope for a win. There are double and triple bars, lucky 7’s, and of course, the nudges. If your bar has a “nudge,” which is an arrow displayed pointing up or down, it will be bumped in that direction when the reels stop, possibly putting it on the payline for a win.',
    tools: 'Illustrator, Photoshop, After Effects and Xcode',
    teamImage: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/400X-Baby-Gator.png',
    team: 'Purple Gator and LED Gaming',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/doubleLuck/DoubleLuckIconX1024.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/doubleLuck/itunes-screenshot.png'},
  { title: 'Double Luck Nudge Slots',
    topic: 'UI DESIGN - App Store Detail 1',
    tools: 'Illustrator',
    description: 'This is a detailed mockup of Double Luck Nudge',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/doubleLuck/DoubleLuckIconX1024.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/doubleLuck/App-Store-Screenshots6-1.png'},
  { title: 'Double Luck Nudge Slots',
    topic: 'UI DESIGN - App Store Detail 2',
    tools: 'Illustrator',
    description: 'This is a detailed mockup of Double Luck Nudge',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/doubleLuck/DoubleLuckIconX1024.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/doubleLuck/App-Store-Screenshots6-2.png'
  }],
    [
  { title: 'Muncher Man',
    description: 'Muncher Man is a maze munching arcade classic design for the Apple Watch. MuncherMan, PurpMan, and Wendy are ready to munch their way through mazes and devour anything standing in their way. Dip and dodge the pesky Munchkins to sweet victory. You can control your Muncher via the Apple Watch buttons or the iPhone swipe controls.',
    tools: 'Illustrator, Photoshop, After Effects and Xcode',
    teamImage: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/400X-Baby-Gator.png',
    team: 'Purple Gator',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/muncherMan/Muncher-Man-Final4-1024-Rounded.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/muncherMan/itunes-screenshot.png'},
  { title: 'Muncher Man',
    topic: 'UI DESIGN - App Store Detail 1',
    tools: 'Illustrator and Photoshop',
    description: 'This is a detailed mockup of Muncher Man',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/muncherMan/Muncher-Man-Final4-1024-Rounded.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/muncherMan/1.png'},
  { title: 'Muncher Man',
    topic: 'UI DESIGN - App Store Detail 2',
    tools: 'Illustrator and Photoshop',
    description: 'This is a detailed mockup of Muncher Man',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/muncherMan/Muncher-Man-Final4-1024-Rounded.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/muncherMan/3.png'
  }],
      [
  { title: 'Trivios',
    description: 'Trivios is a real-time trivia game that allows players to win awesome prizes by playing one of four unique trivia game modes.  Players can also engage socially via their profile, live and offline messaging, and competing with or against each other!  Rather than giving out worthless XP points for playing a game, we are providing our players with a fun and engaging challenge that rewards them for their skill and participation.',
    tools: 'Illustrator, Photoshop, After Effects, Final Cut Pro and Xcode',
    teamImage: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/400X-Baby-Gator.png',
    team: 'Purple Gator',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/trivios/1024X-app-icon-1024.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/trivios/iTunes-Mock-Up+cropped.png'},
  { title: 'Trivios',
    topic: 'UI DESIGN - App Store Detail',
    tools: 'Illustrator and Photoshop',
    description: 'This is a detailed mockup of Trivios',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/trivios/1024X-app-icon-1024.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/trivios/Apple_iPhone4-2.png'},
  { title: 'Trivios',
    topic: 'MOTION GRAPHICS - Demo Video',
    tools: 'Illustrator, After Effects and Final Cut Pro',
    description: 'This is a detailed mockup of Trivios',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/trivios/1024X-app-icon-1024.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/trivios/triVios+1.2+Video+Final+(Official)+30s+-+1334X750.mov'
  }],
  ]
}