module.exports = {
  data: [
  [
  { title: 'CannaCo',
    description: 'CannaCo is an International Architecture Competition entry held by the Bee Breeders Architecture Competition Organizers to design a theoretical Cannabis Bank. CannaCo placed in the Top 40, qualifying for the final round of the international competition. ',
    tools: 'Rhino, Sketchup, AutoCAD, V-Ray, Illustrator, and Photoshop',
    teamImage: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/SamZoll-Logo-2017.svg',
    team: 'Army of 1',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo-Logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo+-+1.jpg'},
  { title: 'CannaCo',
    topic: 'UX DESIGN',
    tools: 'Rhino, Sketchup, AutoCAD, V-Ray, Illustrator, and Photoshop',
    description: 'Slide 2.',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo-Logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo+-+2.jpg'
  },
  { title: 'CannaCo',
    topic: 'UX DESIGN',
    tools: 'Rhino, Sketchup, AutoCAD, V-Ray, Illustrator, and Photoshop',
    description: 'Slide 3.',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo-Logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo+-+3.jpg'
  },
  { title: 'CannaCo',
    topic: 'UX DESIGN',
    tools: 'Rhino, Sketchup, AutoCAD, V-Ray, Illustrator, and Photoshop',
    description: 'Slide 4.',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo-Logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo+-+4.jpg'}
  ],
  [
  { title: 'CannaCo',
    description: "CannaCo is a further iteration of the Modern Pharmacy & Hospital of Chicago project, directed by studio Professor Sean Vance. The goal was to explore modern medicine, specifically medical marijuana. By finding new ways to invent and brand a conceptual company, a medical marijuana dispensary was created. Extensive research was conducted in the development of an infographic. This describes how the companies' supply chain would operate, the mechanical and operational functions of how raw materials are treated once they arrive on site, and how the promotional materials and finished products appear once packaged. From business cards to supply-chain management, CannaCo takes an in-depth look on how to create a medical dispensary in Chicago.",
    tools: 'Rhino, Sketchup, AutoCAD, V-Ray, Illustrator, Photoshop, and CNC Laser Cutters',
    teamImage: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/SamZoll-Logo-2017.svg',
    team: 'Army of 1',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/cc-logo.jpg',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/render1.jpg'},
  { title: 'CannaCo',
    topic: 'Rendering',
    tools: 'Rhino, Sketchup, AutoCAD, V-Ray, Illustrator, Photoshop, and CNC Laser Cutters',
    description: 'Rendering with Rhino and V-Ray',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/cc-logo.jpg',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/render2.jpg'},
  { title: 'CannaCo',
    topic: 'Graphic Design',
    tools: 'Rhino, Sketchup, AutoCAD, V-Ray, Illustrator, Photoshop, and CNC Laser Cutters',
    description: 'Infographic',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/cc-logo.jpg',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/infographic1.jpg'},
  { title: 'CannaCo',
    topic: 'Architecture',
    tools: 'Rhino, Sketchup, AutoCAD, V-Ray, Illustrator, Photoshop, and CNC Laser Cutters',
    description: 'Axonometric Diagram',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/cc-logo.jpg',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/infographic2.jpg'
  },
  { title: 'CannaCo',
    topic: 'Architecture',
    tools: 'Rhino, Sketchup, AutoCAD, V-Ray, Illustrator, Photoshop, and CNC Laser Cutters',
    description: 'Plans, Sections, and Presentation Photo',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/cc-logo.jpg',
    content: ['https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/section1.jpg', 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/section2.jpg', 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/plan0.jpg', 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/plan1.jpg', 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/plan2.jpg', 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/ccphoto.jpg', 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/ccwebsite.png']
    }
  ],
  [
  { title: 'CannaCo',
    description: 'The graphics displayed are the first iteration of the CannaCo Project series. The focus of this project is to create a medical facility that operates as a pharmacy and hospital, while also having the capacity to process its own medicine on site. In the current stage of this project, the building is designed to include a processing and storage space underground, a grand entrance and unloading dock on the ground floor, a pharmacy and hospital on the first floor, and a patio and lounge on the top level.',
    tools: 'Rhino, Sketchup, AutoCAD, Illustrator, and Photoshop',
    teamImage: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/SamZoll-Logo-2017.svg',
    team: 'Army of 1',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo-Logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v1/First-Rendering-1.1.jpg'},
  { title: 'CannaCo',
    topic: 'Architecture',
    tools: 'Rhino, Sketchup, AutoCAD, Illustrator, and Photoshop',
    description: 'Process / User Flow Diagram',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo-Logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v1/medicine+processing+diagram.jpg'
  },
  { title: 'CannaCo',
    topic: 'Architecture',
    tools: 'Rhino, Sketchup, AutoCAD, Illustrator, and Photoshop',
    description: 'Plans',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo-Logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v1/FINAL+PLANS+MIDTERM-04.jpg'
  },
  { title: 'CannaCo',
    topic: 'Architecture',
    tools: 'Rhino, Sketchup, AutoCAD, Illustrator, and Photoshop',
    description: 'Section',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo-Logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v1/SECTION+MIDTERM-01.jpg'}
  ],
    [
  { title: 'Muncher Man',
    description: 'Muncher Man is a maze munching arcade classic design for the Apple Watch. MuncherMan, PurpMan, and Wendy are ready to munch their way through mazes and devour anything standing in their way. Dip and dodge the pesky Munchkins to sweet victory. You can control your Muncher via the Apple Watch buttons or the iPhone swipe controls.',
    tools: 'Illustrator, Photoshop, After Effects and Xcode',
    teamImage: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/400X-Baby-Gator.png',
    team: 'Purple Gator',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/muncherMan/Muncher-Man-Final4-1024-Rounded.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/muncherMan/itunes-screenshot.png'},
  { title: 'Muncher Man',
    topic: 'UI DESIGN - App Store Detail 1',
    tools: 'Illustrator and Photoshop',
    description: 'This is a detailed mockup of Muncher Man',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/muncherMan/Muncher-Man-Final4-1024-Rounded.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/muncherMan/1.png'},
  { title: 'Muncher Man',
    topic: 'UI DESIGN - App Store Detail 2',
    tools: 'Illustrator and Photoshop',
    description: 'This is a detailed mockup of Muncher Man',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/muncherMan/Muncher-Man-Final4-1024-Rounded.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/muncherMan/3.png'
  }],
      [
  { title: 'Trivios',
    description: 'Trivios is a real-time trivia game that allows players to win awesome prizes by playing one of four unique trivia game modes.  Players can also engage socially via their profile, live and offline messaging, and competing with or against each other!  Rather than giving out worthless XP points for playing a game, we are providing our players with a fun and engaging challenge that rewards them for their skill and participation.',
    tools: 'Illustrator, Photoshop, After Effects, Final Cut Pro and Xcode',
    teamImage: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/400X-Baby-Gator.png',
    team: 'Purple Gator',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/trivios/1024X-app-icon-1024.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/trivios/iTunes-Mock-Up+cropped.png'},
  { title: 'Trivios',
    topic: 'UI DESIGN - App Store Detail',
    tools: 'Illustrator and Photoshop',
    description: 'This is a detailed mockup of Trivios',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/trivios/1024X-app-icon-1024.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/trivios/Apple_iPhone4-2.png'},
  { title: 'Trivios',
    topic: 'MOTION GRAPHICS - Demo Video',
    tools: 'Illustrator, After Effects and Final Cut Pro',
    description: 'This is a detailed mockup of Trivios',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/trivios/1024X-app-icon-1024.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/trivios/triVios+1.2+Video+Final+(Official)+30s+-+1334X750.mov'
  }],
  ]
}