module.exports = {
  data: [
  [
  { title: 'Design Competition',
    description: 'CannaCo is an International Architecture Competition entry held by the Bee Breeders Architecture Competition Organizers to design a theoretical Cannabis Bank. CannaCo placed in the Top 40, qualifying for the final round of the international competition. ',
    tools: 'Rhino, Sketchup, AutoCAD, V-Ray, Illustrator, and Photoshop',
    teamImage: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/SamZoll-Logo-2017.svg',
    team: 'Solo Project',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo-Logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo+-+1.jpg'},
  { title: 'CannaCo',
    topic: 'UX DESIGN',
    tools: 'Rhino, Sketchup, AutoCAD, V-Ray, Illustrator, and Photoshop',
    description: 'Slide 2.',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo-Logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo+-+2.jpg'
  },
  { title: 'CannaCo',
    topic: 'UX DESIGN',
    tools: 'Rhino, Sketchup, AutoCAD, V-Ray, Illustrator, and Photoshop',
    description: 'Slide 3.',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo-Logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo+-+3.jpg'
  },
  { title: 'CannaCo',
    topic: 'UX DESIGN',
    tools: 'Rhino, Sketchup, AutoCAD, V-Ray, Illustrator, and Photoshop',
    description: 'Slide 4.',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo-Logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo+-+4.jpg'}
  ],
  [
  { title: 'CannaCo',
    description: 'The graphics displayed are the first iteration of the CannaCo Project series. The focus of this project is to create a medical facility that operates as a pharmacy and hospital, while also having the capacity to process its own medicine on site. In the current stage of this project, the building is designed to include a processing and storage space underground, a grand entrance and unloading dock on the ground floor, a pharmacy and hospital on the first floor, and a patio and lounge on the top level.',
    tools: 'Rhino, Sketchup, AutoCAD, Illustrator, and Photoshop',
    teamImage: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/SamZoll-Logo-2017.svg',
    team: 'Solo Project',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo-Logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v1/First-Rendering-1.1.jpg'},
  { title: 'CannaCo',
    topic: 'Architecture',
    tools: 'Rhino, Sketchup, AutoCAD, Illustrator, and Photoshop',
    description: 'Process / User Flow Diagram',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo-Logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v1/medicine+processing+diagram.jpg'
  },
  { title: 'CannaCo',
    topic: 'Architecture',
    tools: 'Rhino, Sketchup, AutoCAD, Illustrator, and Photoshop',
    description: 'Plans',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo-Logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v1/FINAL+PLANS+MIDTERM-04.jpg'
  },
  { title: 'CannaCo',
    topic: 'Architecture',
    tools: 'Rhino, Sketchup, AutoCAD, Illustrator, and Photoshop',
    description: 'Section',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/cannaco/CannaCo-Logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v1/SECTION+MIDTERM-01.jpg'}
  ],
  [
  { title: 'Ann Arbor Music School',
    description: 'For the second iteration of the Ann Arbor Music School, I designed an space that was focused on improving social interaction. The school is organized in a simple manner around two central helixes: one houses the classrooms and learning environments, while the other supports spaces designed for the students with individual and group learning pods where students can escape to practice music or study. If two students wanted to practice together, they could link their spaces for live audio feed, connecting two physically distant spaces in a way that feels as if they were joined. To add to this effect, lights would change color and intensity at the same rhythm or tempo to show visually that the spaces were connected. This highlights the internal connection to the exterior occupants of the surrounding building. Including this audio and visual communication aspect of this building allows students to enjoy privacy and personal space, while giving them the added benefit of being able to work on a group project or rehearse for an upcoming show in a collaborative manor.',
    tools: 'Rhino, Sketchup, AutoCAD, Illustrator, and Photoshop',
    teamImage: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/SamZoll-Logo-2017.svg',
    team: 'Solo Project',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/AA+Music+v2/AAMusic2-Logo.jpg',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/AA+Music+v2/Rendered-in-Site1.jpg'},
  { title: 'Ann Arbor Music School',
    topic: 'Architecture',
    tools: 'Rhino, Sketchup, AutoCAD, Illustrator, and Photoshop',
    description: 'This is a graphic representing the numerous iterations it to took get to completed design.',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/AA+Music+v2/AAMusic2-Logo.jpg',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/AA+Music+v2/Tile+UG4.jpg'}
  ],
  [
  { title: 'Ann Arbor Music School',
    description: "The Ann Arbor School of Music was part of an exploration that dealt with how to design an educational environment with preference to music students. Before the conceptual stage of design, I performed research delving into various ideologies and methods of education. The sociology and pedagogy of academia throughout history in our society focused my interest on the Progressive Education movement in the late 19th century and the Open Air Schools of the late 20's and 30's. John Dewey, one of the leaders of the Progressive Education movement, advocated for education that took into account the student’s status as a social being. Studying the Openluchtschool (Open Air School) in Amsterdam by Johannes Duiker helped me create a formal expression of how I designed division of space for the conception of this school. The project presented here was my first attempt at the formulation of a school. In the second iteration of this project, I was better able to clarify my aspirations regarding how I intended this School of Music to operate.",
    teamImage: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/SamZoll-Logo-2017.svg',
    team: 'Solo Project',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/AA+Music+v2/AAMusic2-Logo.jpg',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/AA+Music+v1/IMG_1525.JPG'},
  { title: 'Ann Arbor Music School',
    topic: 'Architecture',
    tools: 'Rhino, AutoCAD, Illustrator, and Photoshop',
    description: 'Floor Plans.',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/AA+Music+v2/AAMusic2-Logo.jpg',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/AA+Music+v1/FINAL+3+PLANS.jpg'},
  { title: 'Ann Arbor Music School',
    topic: 'Architecture',
    tools: 'Rhino, AutoCAD, Illustrator, and Photoshop',
    description: 'Section Sketch',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/AA+Music+v2/AAMusic2-Logo.jpg',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/AA+Music+v1/SECTION+PERSPECTIVE.jpg'},
  { title: 'Ann Arbor Music School',
    topic: 'Architecture',
    tools: 'Rhino and Illustrator',
    description: 'Exterior Facade Diagram',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/AA+Music+v2/AAMusic2-Logo.jpg',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/AA+Music+v1/EXTERIOR+FACADE.jpg'},
  { title: 'Ann Arbor Music School',
    topic: 'Architecture',
    tools: 'Rhino, Sketchup, AutoCAD, Illustrator, and Photoshop',
    description: 'This is a gallery of the 1/16th Scale Model with fiber optic cables and LED lights',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/AA+Music+v2/AAMusic2-Logo.jpg',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/AA+Music+v1/EXTERIOR+FACADE.jpg'}
  ],
  [
  { title: 'Hand Drawing',
    description: "In this introductory drawing class, our class was assigned to draw an interspatial environment on campus. I was captivated by the staircase presented here for the long perspectival view afforded when approaching this transitional area. One of the more complicating caveats of this exercise was that no rulers or erasers were allowed in the creation of these drawings. Due to this stipulation, the seeming uncomplicated depiction took quite a long time to reach completion.",
    tools: 'Pencil and Paper. No Erasers or Rulers.',
    teamImage: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/SamZoll-Logo-2017.svg',
    team: 'Solo Project',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/Hand+Drawing/drawing-logo.svg',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/Hand+Drawing/IMG_7937.jpg'},
  { title: 'Ann Arbor Music School',
    topic: 'Architecture',
    tools: 'Pencil and Paper. No Erasers or Rulers.',
    description: 'One Point Perspective',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/Hand+Drawing/drawing-logo.svg',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/Hand+Drawing/IMG_7942.jpg'}
  ],
  [
  { title: 'Maison de Verre',
    description: "After studying the Maison de Verre, it was discovered that different patterns of circulation tend to preference certain members of the household. The house was designed so that residents would have very specific routes when navigating the home. The lower level was set up so that the husband, also a doctor, could receive and treat his patients. The middle level contains all the residential living spaces, while the top level contains the bedrooms. Throughout these three levels, it is evident from the diagrams above that the house preferences the male as opposed to the female inhabitants.",
    tools: 'Rhino, V-Ray, Final Cut Pro, Illustrator and Photoshop',
    teamImage: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/SamZoll-Logo-2017.svg',
    team: 'Solo Project',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/Maison+de+Verre/maison+de+verre-logo.jpg',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/Maison+de+Verre/Maison-de-Verre-Final-Poster.jpg'},
  { title: 'Maison de Verre',
    topic: 'Architecture',
    tools: 'Rhino, V-Ray, Final Cut Pro, Illustrator and Photoshop',
    description: 'Exterior Study',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/Maison+de+Verre/maison+de+verre-logo.jpg',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/Maison+de+Verre/Maison+de+Verre+exterior.jpg'},
  { title: 'Maison de Verre',
    topic: 'Architecture',
    tools: 'Rhino, V-Ray, Final Cut Pro, Illustrator and Photoshop',
    description: 'Interior Study',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/Maison+de+Verre/maison+de+verre-logo.jpg',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/Maison+de+Verre/Maison+de+Verre+interior.jpg'},
    { title: 'Maison de Verre',
    topic: 'Final Photo',
    tools: 'Creativity!',
    description: 'Power Pose.',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/Maison+de+Verre/maison+de+verre-logo.jpg',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/Maison+de+Verre/final-photo.jpg'}
  ],
  [
  { title: 'Open Air School',
    description: "In an effort to study various types of school designs, I created a detailed, illustrated book breaking down the essential technicalities that ultimately compose the character of the Open Air School. This project was conducted to better understand what characteristics are important in designing an educational environment. After compiling this information, I was better prepared for the task of designing my own school.",
    tools: 'Illustrator, InDesign, Photoshop, Rhino and AutoCAD',
    teamImage: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/SamZoll-Logo-2017.svg',
    team: 'Solo Project',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/Hand+Drawing/drawing-logo.svg',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/Hand+Drawing/IMG_7937.jpg'}
  ],
  [
  { title: 'Universal Character System',
    description: "The purpose of this project was to create a database of physical human characteristics that could be easily manipulated by the user dragging a slider. These characteristics would include skin tones, body weights, body structures, genders, and other unique features complied from databases of real people who had been photographed in order to use the images to create different types of high-resolution, three-dimensional characters. A special aspect of this project is that it enables multiple human characteristics to be combined in order to create an infinite variety of dynamic skin tones and features. This system would be helpful in real world applications by professions in need of a quick human model to demonstrate something that the user could determine.",
    tools: 'Mudbox and Photoshop',
    teamImage: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/UM+3D/um3dlab-logo.jpg',
    team: 'UM3D Lab',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/UM+3D/um3dlab-logo.jpg',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/UM+3D/Research-Poster.jpg'},
  { title: 'Universal Character System',
    topic: '3D Character Design',
    tools: 'Mudbox',
    description: 'Mudbox Character Close-Up',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/UM+3D/um3dlab-logo.jpg',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/UM+3D/character.png'}
  ],
  [
  { title: '2D Drawings to 3D Models',
    description: "During a summer internship my junior year of high school, I worked at a small architecture firm, Bob Brobson Inc. and created the following 3D Models. The gallery of images shows a small portion of the buildings that were converted into 3D models. Shortly after learning how to use the 3D software, Google Sketchup, I was given 2D drawings (plans and sections) of the past projects the firm had worked on. Throughout the summer, I diligently performed the task of taking all these drawings and converting them into highly detailed 3D models in order to show future clients demonstrations of the firm’s work. ",
    tools: 'Sketchup',
    teamImage: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/Bob+Brobson/brobson-logo.jpg',
    team: 'Bob Brobson',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/Bob+Brobson/brobson-logo.jpg',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/Hand+Drawing/IMG_7937.jpg'}
  ]
  ]
}

//  [
  // { title: 'CannaCo',
  //   description: "CannaCo is a further iteration of the Modern Pharmacy & Hospital of Chicago project, directed by studio Professor Sean Vance. The goal was to explore modern medicine, specifically medical marijuana. By finding new ways to invent and brand a conceptual company, a medical marijuana dispensary was created. Extensive research was conducted in the development of an infographic. This describes how the companies' supply chain would operate, the mechanical and operational functions of how raw materials are treated once they arrive on site, and how the promotional materials and finished products appear once packaged. From business cards to supply-chain management, CannaCo takes an in-depth look on how to create a medical dispensary in Chicago.",
  //   tools: 'Rhino, Sketchup, AutoCAD, V-Ray, Illustrator, Photoshop, and CNC Laser Cutters',
  //   teamImage: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/SamZoll-Logo-2017.svg',
  //   team: 'Solo Project',
  //   logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/cc-logo.jpg',
  //   content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/render1.jpg'},
  // { title: 'CannaCo',
  //   topic: 'Rendering',
  //   tools: 'Rhino, Sketchup, AutoCAD, V-Ray, Illustrator, Photoshop, and CNC Laser Cutters',
  //   description: 'Rendering with Rhino and V-Ray',
  //   logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/cc-logo.jpg',
  //   content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/render2.jpg'},
  // { title: 'CannaCo',
  //   topic: 'Graphic Design',
  //   tools: 'Rhino, Sketchup, AutoCAD, V-Ray, Illustrator, Photoshop, and CNC Laser Cutters',
  //   description: 'Infographic',
  //   logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/cc-logo.jpg',
  //   content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/infographic1.jpg'},
  // { title: 'CannaCo',
  //   topic: 'Architecture',
  //   tools: 'Rhino, Sketchup, AutoCAD, V-Ray, Illustrator, Photoshop, and CNC Laser Cutters',
  //   description: 'Axonometric Diagram',
  //   logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/cc-logo.jpg',
  //   content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/infographic2.jpg'
  // },
  // { title: 'CannaCo',
  //   topic: 'Architecture',
  //   tools: 'Rhino, Sketchup, AutoCAD, V-Ray, Illustrator, Photoshop, and CNC Laser Cutters',
  //   description: 'Plans, Sections, and Presentation Photo',
  //   logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/cc-logo.jpg',
  //   content: ['https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/section1.jpg', 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/section2.jpg', 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/plan0.jpg', 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/plan1.jpg', 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/plan2.jpg', 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/ccphoto.jpg', 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/2d3d/CannaCo+v2/ccwebsite.png']
  //   }
  // ],