module.exports = {
  data: [
  [
  { title: 'Truck Hunt SF',
    description: 'Truck Hunt allows users in San Francisco to find the nearest food trucks, place an order, and pick up when ready. Truck Hunt features both consumer and vendor facing interfaces so that truck vendors can also log onto the app to view incoming orders, past orders, and customer analytics.',
    responsibilities: 'UI/UX design, React/Redux implementation, consumer user flow with maps and search auto-complete, and vendor management portal with D3-based analytics.',
    tools: 'React, React-Router, Redux, NodeJS, Express, PosgreSQL, Mapbox, Bootstrap, and Semantic UI',
    teamImage: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/SamZoll-Logo-2017.svg',
    team: 'Personal project built with an awesome team of four.',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/truckHunt/truck-hunt-logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/truckHunt/truck-hunt-static.png',
    location: 'San Francisco',
    locationImage: 'url',
    date: 'April 2017'
  },
  { title: 'Truck Hunt SF',
    description: 'This is a quick gif guided tour.',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/truckHunt/truck-hunt-logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/truckHunt/Trunk-Hunt-HQ.gif',
    location: 'San Francisco',
    locationImage: 'url',
    date: 'April 2017'},
  { title: 'Truck Hunt SF',
    description: 'This is a video guided tour.',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/truckHunt/truck-hunt-logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/truckHunt/truck+hunt+demo+(720p).mp4',
    location: 'San Francisco',
    locationImage: 'url',
    date: 'April 2017'
  }],
  [
  { title: 'Oranges 2 Oranges',
    description: 'Oranges 2 Oranges is a realtime MMO based off the board game Apples to Apples. 4 players join a game and take turns coming up with the wittiest responses to each prompt. Player with the most judge voted points wins. Players can enjoy playing an endless-flyer game as other players connect in the waiting room.',
    responsibilities: 'Endless-flyer loading game, automated emailing tool, responsive UI and fluid UX improving animations.',
    tools: 'React, React-Router, Socket.io, Phaser.io, NodeJS, Express, MongoDB, and Bootstrap',
    teamImage: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/SamZoll-Logo-2017.svg',
    team: 'Personal project built with an awesome team of four.',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/oranges2oranges/oranges2oranges-logo-reduced.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/oranges2oranges/oranges2oranges-static.png',
    location: 'San Francisco',
    locationImage: 'url',
    date: 'March 2017'
  },
  { title: 'Oranges 2 Oranges',
    description: 'This is a quick gif guided tour.',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/oranges2oranges/oranges2oranges-logo-reduced.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/oranges2oranges/oranges_2_oranges.gif',
    location: 'San Francisco',
    locationImage: 'url',
    date: 'March 2017'
  },
  { title: 'Oranges 2 Oranges',
    description: 'This is a video guided tour.',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/oranges2oranges/oranges2oranges-logo-reduced.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/oranges2oranges/Oranges+2+Oranges+2X(reduced).m4v',
    location: 'San Francisco',
    locationImage: 'url',
    date: 'March 2017'
  }],
  [
  { title: 'Ticket Champ',
    description: 'Ticket Champ is a ticket price comparison app. When trying to find the best price for tickets, Ticket Champ allows you to search your desired event and compare prices from multiple vendors.',
    responsibilities: "App UI/UX design and implementation, integrated multiple ticket vendor API's and consolidated server requests for minimal 3rd party API reliance.",
    tools: 'React, NodeJS, Express, MySQL, Bootstrap and CSS Flexbox',
    teamImage: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/SamZoll-Logo-2017.svg',
    team: 'Personal project built with an awesome team of four.',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/ticketChamp/ticket-champ-logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/ticketChamp/Ticket-Champ-Static.png',
    location: 'San Francisco',
    locationImage: 'url',
    date: 'March 2017'
  },
  { title: 'Ticket Champ',
    description: 'This is a quick gif guided tour.',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/ticketChamp/ticket-champ-logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/ticketChamp/ticket-champ.gif',
    location: 'San Francisco',
    locationImage: 'url',
    date: 'March 2017'
  },
  { title: 'Ticket Champ',
    description: 'This is a video guided tour.',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/ticketChamp/ticket-champ-logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/ticketChamp/Ticket+Champ+720p.mp4',
    location: 'San Francisco',
    locationImage: 'url',
    date: 'March 2017'
  },
  { title: 'Ticket Champ',
    description: 'This is the wireframe sketch that was converted to a greyscale mockup using Adobe Illustrator',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/ticketChamp/ticket-champ-logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/ticketChamp/wireframe.png',
    location: 'San Francisco',
    locationImage: 'url',
    date: 'March 2017'
  }],
  [
  { title: 'Trivia Night',
    description: "Trivia Night enables bar owners to create white-labeled trivia games with personalized dashboard in a matter of seconds. Users BYOD and create a trivia game as friends join the socket-based HTML5 game, and compete for prizes of the bar's choice. Bystanders can follow along by watching the venue’s TV's to view questions and leaderboards in real-time.",
    responsibilities: 'Trivia Night Demo website, app UI/UX, and all promotional videos + materials.',
    tools: 'Bootstrap, jQuery, NodeJS, Express, Photoshop, Illustrator, After Effects, and Final Cut Pro',
    teamImage: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/400X-Baby-Gator.png',
    team: 'Purple Gator',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/triviaNight/trivia-night-logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/triviaNight/homescreen.png',
    location: 'Chicago',
    locationImage: 'url',
    date: '2017'
  },
  { title: 'Trivia Night',
    description: 'Detailed desktop site mockup.',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/triviaNight/trivia-night-logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/triviaNight/Trivia-Night-Mockup.png',
    location: 'Chicago',
    locationImage: 'url',
    date: '2017'
  },
  { title: 'Trivia Night',
    description: 'Marketing demo and product experience tour.',
    logo: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/triviaNight/trivia-night-logo.png',
    content: 'https://s3-us-west-1.amazonaws.com/zollstorage/portfolio/triviaNight/Trivia-Night-720P.mp4',
    location: 'Chicago',
    locationImage: 'url',
    date: '2017'
  }]
  ]
}